id: A1B9DB1BF
base_file: f89F8.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:48:10.117301
  last_modified_at: 2022-05-30 20:48:10.117304
