id: A1B9DB1BF
base_file: fB900.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:48:10.122187
  last_modified_at: 2022-05-30 20:48:10.122190
