id: A1B9DB1BF
base_file: fE629.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:48:10.125607
  last_modified_at: 2022-05-30 20:48:10.125610
